/* =====================================================================
   EVOCATIONS-DATA.JS — Appendice "Évocations" des Parchemins de lecture
   ---------------------------------------------------------------------
   10 sections de vocabulaire (100 mots chacune), un texte utilisant une
   partie de ces mots, et 20 exercices (famille / synonymes / antonymes /
   féminin) par section. Données extraites du document fourni par
   l'enseignant — ne pas modifier à la main, régénérer depuis la source
   si le contenu doit changer.
   ===================================================================== */

const EVOCATIONS_DATA = [
  {
    id: 1,
    titre: "1. L'école et l'apprentissage",
    vocabulaire: ["abandon", "achat", "acier", "acteur", "actrice", "amateur", "amatrice", "animaux", "arrivée", "art", "article", "artisan", "artisane", "artiste", "artère", "bagage", "baignoire", "cage", "cahier", "canal", "carnaval", "carte", "chômage", "classe", "colonne", "confort", "conquête", "cours", "crayon", "cri", "discours", "encre", "examen", "exercice", "exigence", "fameuse", "fameux", "flotte", "fontaine", "formule", "foyer", "gens", "golfe", "gonfler", "gémir", "histoire", "idée", "incendie", "jambon", "lecture", "lettre", "liquide", "livre", "maire", "marque", "marteau", "moelle", "mot", "moteur", "moulin", "mémoire", "métier", "note", "origine", "partage", "parti", "partie", "pause", "pensée", "pneu", "projet", "propreté", "quartier", "question", "retraite", "rien", "robe", "règle", "réalité", "récit", "résultat", "science", "secours", "statue", "style", "tache", "tarte", "tendance", "texte", "thé", "théorie", "théâtre", "titre", "univers", "usage", "vers", "vive", "zèle", "école", "écriture"],
    texte: "Je pense que l'école est très importante pour tous les enfants. C'est là qu'on apprend à lire, à écrire et à compter. Moi, j'aime bien ma classe parce que mon enseignante explique bien et qu'elle est patiente. Elle nous donne des cahiers et des crayons pour travailler. Parfois, on a un examen et ce n'est pas toujours facile, mais c'est normal. Il faut faire des exercices pour comprendre les leçons. À l'école, on apprend aussi l'histoire et la science. On lit des livres et on écrit des textes courts. On apprend des règles pour bien vivre ensemble. Le plus important, c'est le partage et le respect des autres. Quand on fait un projet en équipe, on se sent fier et on apprend à écouter. On fait aussi du sport, de la musique et du dessin. L'école nous aide à grandir et à devenir plus autonomes. Elle nous prépare à avoir un métier plus tard, même si on ne sait pas encore lequel. Elle nous donne confiance en nous. Je trouve que c'est une chance d'y aller chaque jour. Même quand c'est difficile, on apprend toujours quelque chose de nouveau. C'est pour ça que je défends l'école et que je dis qu'il faut y aller.",
    motsUtilises: ["classe", "examen", "métier", "partage", "projet", "science"],
    exercices: [
      { categorie: "Famille de mots", indice: "artisanat", reponse: "artisan" },
      { categorie: "Famille de mots", indice: "scolarité", reponse: "école" },
      { categorie: "Famille de mots", indice: "lettré", reponse: "lettre" },
      { categorie: "Famille de mots", indice: "étudiant", reponse: "étude" },
      { categorie: "Famille de mots", indice: "écrivain", reponse: "écriture" },
      { categorie: "Synonymes", indice: "bouquin", reponse: "livre" },
      { categorie: "Synonymes", indice: "interrogation", reponse: "question" },
      { categorie: "Synonymes", indice: "réflexion", reponse: "pensée" },
      { categorie: "Synonymes", indice: "évaluation", reponse: "examen" },
      { categorie: "Synonymes", indice: "conte", reponse: "histoire" },
      { categorie: "Antonymes", indice: "départ", reponse: "arrivée" },
      { categorie: "Antonymes", indice: "emploi", reponse: "chômage" },
      { categorie: "Antonymes", indice: "oubli", reponse: "mémoire" },
      { categorie: "Antonymes", indice: "ignorance", reponse: "science" },
      { categorie: "Antonymes", indice: "désordre", reponse: "règle" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "fameux", reponse: "fameuse" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "parti", reponse: "partie" },
    ]
  },
  {
    id: 2,
    titre: "2. La famille, les personnes et les métiers",
    vocabulaire: ["acheteuse", "actrice", "adieu", "adulte", "amie", "amitié", "ange", "argent", "auteur", "auteure", "barbe", "bouche", "boucher", "boucherie", "boulanger", "chasseur", "chaud", "cousin", "cousine", "creux", "croire", "croix", "célèbre", "danse", "danseuse", "demeure", "deuil", "dresser", "effroi", "erreur", "essai", "facteur", "factrice", "famille", "fantôme", "fille", "fillette", "froid", "frère", "galop", "garçon", "gibier", "grandeur", "géant", "hauteur", "homme", "héros", "image", "lame", "lecteur", "lectrice", "lenteur", "magicien", "marge", "matériel", "mauvais", "mille", "miroir", "monde", "mystère", "médecin", "odeur", "os", "parent", "paroi", "passion", "patron", "patronne", "peinture", "police", "poète", "preuve", "prime", "prière", "prénom", "prêt", "prêtre", "pureté", "reine", "roi", "ruine", "salut", "soeur", "soldat", "sorcier", "tente", "trait", "vacances", "veine", "vie", "visite", "visiteur", "voisin", "voisine", "vol", "voyage", "voyageur", "vrai", "vérité", "épave"],
    texte: "À mon avis, la famille est la chose la plus importante dans la vie. Ce n'est pas l'argent qui rend heureux, même si on en a besoin pour vivre. Ce qui compte vraiment, c'est l'amour entre les personnes qui s'aiment et qui prennent soin les unes des autres. Dans ma famille, il y a mes parents, ma soeur et mon frère. On s'aide beaucoup à la maison pour les tâches. On mange ensemble le soir et on parle de notre journée, de ce qui s'est bien passé. J'ai aussi une amie qui habite à côté de chez moi. Elle est comme une soeur pour moi. On joue ensemble après l'école et on se raconte des secrets. Mes voisins sont gentils aussi et on les salue souvent. Il y a un boulanger qui fait du très bon pain au bout de la rue. Le facteur passe chaque matin avec le courrier et il sourit toujours. Le médecin nous soigne quand on est malade. Chaque personne a un rôle important dans le quartier. Le monde est fait de rencontres et de moments partagés. Il faut prendre soin de sa famille et de ses amis. C'est ça qui donne du sens à la vie. C'est plus fort que tout le reste. Je crois que sans famille et sans amis, on se sent seul et triste.",
    motsUtilises: ["amie", "boulanger", "facteur", "famille", "frère", "monde", "médecin", "soeur", "vie"],
    exercices: [
      { categorie: "Famille de mots", indice: "parental", reponse: "parent" },
      { categorie: "Famille de mots", indice: "amical", reponse: "amie" },
      { categorie: "Famille de mots", indice: "voisinage", reponse: "voisin" },
      { categorie: "Famille de mots", indice: "lectorat", reponse: "lecteur" },
      { categorie: "Famille de mots", indice: "patronal", reponse: "patron" },
      { categorie: "Synonymes", indice: "copine", reponse: "amie" },
      { categorie: "Synonymes", indice: "clan", reponse: "famille" },
      { categorie: "Synonymes", indice: "docteur", reponse: "médecin" },
      { categorie: "Synonymes", indice: "sincérité", reponse: "vérité" },
      { categorie: "Synonymes", indice: "existence", reponse: "vie" },
      { categorie: "Antonymes", indice: "glacial", reponse: "chaud" },
      { categorie: "Antonymes", indice: "brûlant", reponse: "froid" },
      { categorie: "Antonymes", indice: "mensonge", reponse: "vérité" },
      { categorie: "Antonymes", indice: "mort", reponse: "vie" },
      { categorie: "Antonymes", indice: "ennemies", reponse: "amie" },
      { categorie: "Féminin", indice: "facteur", reponse: "factrice" },
      { categorie: "Féminin", indice: "lecteur", reponse: "lectrice" },
      { categorie: "Féminin", indice: "patron", reponse: "patronne" },
      { categorie: "Féminin", indice: "voisin", reponse: "voisine" },
      { categorie: "Féminin", indice: "cousin", reponse: "cousine" },
    ]
  },
  {
    id: 3,
    titre: "3. La maison et la vie quotidienne",
    vocabulaire: ["acheteur", "acheteuse", "acteur", "actrice", "amateur", "amatrice", "artisan", "artisane", "avion", "bague", "bain", "balai", "balle", "billet", "bois", "bout", "caverne", "chambre", "char", "charge", "clavier", "commande", "conflit", "courage", "couteau", "cuisine", "division", "drap", "drapeau", "débat", "décor", "décrire", "décès", "défaut", "défendre", "défense", "délai", "dépense", "dépit", "déplacer", "déranger", "désir", "désirer", "désordre", "détail", "détour", "détresse", "ferme", "feu", "feuille", "filet", "fourrure", "garage", "grenier", "horloge", "immeuble", "jardin", "jeunesse", "linge", "maison", "matelas", "meuble", "monnaie", "montre", "métal", "onde", "outil", "peluche", "pièce", "plaine", "planche", "plante", "planète", "poing", "port", "porte", "potage", "procédé", "qualité", "reprise", "rideau", "roue", "savon", "seau", "soir", "solitude", "souris", "surprise", "tambour", "tapis", "toile", "tour", "train", "violon", "visage", "vision", "voiture", "volant", "écran", "égalité"],
    texte: "Je crois que la maison est beaucoup plus qu'un simple bâtiment avec des murs. C'est un endroit où on se sent en sécurité, aimé et tranquille. Moi, j'aime beaucoup ma chambre parce que c'est calme et que je peux lire ou dessiner sans bruit. J'aime aussi la cuisine quand ma mère prépare à manger, ça sent toujours très bon et ça donne faim. J'aime le jardin où je peux jouer au ballon avec mon frère. Certaines personnes veulent toujours prendre l'avion ou la voiture pour partir très loin en voyage. Elles pensent que c'est plus amusant ailleurs que chez elles. Mais je pense que c'est bien de rester chez soi parfois et de profiter de ce qu'on a. Il faut avoir du courage pour ranger et nettoyer quand il y a du désordre partout. C'est fatigant, mais après on est vraiment content et fier. Une maison propre, avec un bon lit, une table, une lampe et un tapis doux, c'est agréable. On y vit des moments simples, comme regarder un film ou parler ensemble le soir. Il faut la protéger et en prendre soin chaque jour pour s'y sentir bien.",
    motsUtilises: ["chambre", "courage", "cuisine", "désordre", "jardin", "maison", "soir", "tapis", "voiture"],
    exercices: [
      { categorie: "Famille de mots", indice: "ménager", reponse: "maison" },
      { categorie: "Famille de mots", indice: "jardiner", reponse: "jardin" },
      { categorie: "Famille de mots", indice: "culinaire", reponse: "cuisine" },
      { categorie: "Famille de mots", indice: "outiller", reponse: "outil" },
      { categorie: "Famille de mots", indice: "meubler", reponse: "meuble" },
      { categorie: "Synonymes", indice: "logis", reponse: "maison" },
      { categorie: "Synonymes", indice: "parc", reponse: "jardin" },
      { categorie: "Synonymes", indice: "gastronomie", reponse: "cuisine" },
      { categorie: "Synonymes", indice: "ustensile", reponse: "outil" },
      { categorie: "Synonymes", indice: "mobilier", reponse: "meuble" },
      { categorie: "Antonymes", indice: "ordre", reponse: "désordre" },
      { categorie: "Antonymes", indice: "lâcheté", reponse: "courage" },
      { categorie: "Antonymes", indice: "inégalité", reponse: "égalité" },
      { categorie: "Antonymes", indice: "qualité", reponse: "défaut" },
      { categorie: "Antonymes", indice: "paix", reponse: "conflit" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
      { categorie: "Féminin", indice: "acheteur", reponse: "acheteuse" },
      { categorie: "Féminin", indice: "port", reponse: "porte" },
    ]
  },
  {
    id: 4,
    titre: "4. Le corps, les émotions et la santé",
    vocabulaire: ["accident", "accord", "acheteur", "acheteuse", "acteur", "action", "actrice", "amateur", "amatrice", "amour", "angoisse", "arme", "artisan", "artisane", "aspect", "balcon", "barrage", "blessure", "bonheur", "bras", "brassard", "brosse", "cabane", "caisse", "chapeau", "chariot", "coeur", "corps", "couche", "couloir", "coup", "coupable", "courant", "courrier", "couvrir", "côte", "dialogue", "domaine", "dommage", "dossier", "ennui", "envie", "exposer", "exposé", "facteur", "factrice", "faim", "fatigue", "fierté", "fossé", "fureur", "grippe", "grosseur", "guérison", "haine", "haleine", "honneur", "honte", "horreur", "humain", "humeur", "hygiène", "hôpital", "incident", "jambe", "joie", "langue", "larme", "main", "maladie", "malheur", "membre", "nerf", "oeil", "ongle", "orage", "ouvrage", "patience", "peur", "plaie", "plaisir", "poids", "poignet", "pose", "position", "poste", "pouls", "poumon", "rage", "rancune", "remède", "réserve", "rêve", "rêver", "sagesse", "salaire", "sang", "sanglot", "santé", "semaine"],
    texte: "Je vais décrire mon petit frère quand il est malade. Ce matin, il a le visage pâle et les yeux fatigués. Son corps est chaud et son coeur bat vite. Il a mal à la tête et à la jambe gauche. Il a aussi une petite blessure au bras qui lui fait mal quand il bouge. Il ne veut pas manger parce qu'il n'a pas faim et il a un peu la nausée. Il reste couché dans son lit, avec une couverture douce et son toutou préféré. Il a peur d'aller à l'hôpital, il pleure un peu et il appelle maman. Ma mère lui donne un remède avec de l'eau fraîche et elle lui parle doucement. Elle reste à côté de lui pour le rassurer et lui tenir la main. Elle lui raconte une petite histoire pour qu'il s'endorme tranquillement. Au bout de deux jours, il va beaucoup mieux. Il retrouve son sourire, sa joie de vivre et son envie de jouer dehors avec ses amis. Il a de nouveau de l'énergie. C'est un grand bonheur pour toute la famille de le voir en forme et content.",
    motsUtilises: ["blessure", "bonheur", "bras", "coeur", "corps", "envie", "faim", "jambe", "joie", "main", "peur", "remède"],
    exercices: [
      { categorie: "Famille de mots", indice: "cardiaque", reponse: "coeur" },
      { categorie: "Famille de mots", indice: "corporel", reponse: "corps" },
      { categorie: "Famille de mots", indice: "jambier", reponse: "jambe" },
      { categorie: "Famille de mots", indice: "sanguin", reponse: "sang" },
      { categorie: "Famille de mots", indice: "maladif", reponse: "maladie" },
      { categorie: "Synonymes", indice: "allégresse", reponse: "joie" },
      { categorie: "Synonymes", indice: "crainte", reponse: "peur" },
      { categorie: "Synonymes", indice: "épuisement", reponse: "fatigue" },
      { categorie: "Synonymes", indice: "félicité", reponse: "bonheur" },
      { categorie: "Synonymes", indice: "affection", reponse: "amour" },
      { categorie: "Antonymes", indice: "félicité", reponse: "malheur" },
      { categorie: "Antonymes", indice: "santé", reponse: "maladie" },
      { categorie: "Antonymes", indice: "audace", reponse: "peur" },
      { categorie: "Antonymes", indice: "affection", reponse: "haine" },
      { categorie: "Antonymes", indice: "plaisir", reponse: "ennui" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
      { categorie: "Féminin", indice: "acheteur", reponse: "acheteuse" },
      { categorie: "Féminin", indice: "facteur", reponse: "factrice" },
    ]
  },
  {
    id: 5,
    titre: "5. La nature, les animaux et l'environnement",
    vocabulaire: ["absent", "absente", "accrocher", "acheteur", "acheteuse", "acteur", "actrice", "adoration", "agir", "ail", "allumer", "allée", "amateur", "amatrice", "animal", "approche", "araignée", "arbre", "artisan", "artisane", "assemblée", "auto", "automne", "aventure", "baleine", "bavardage", "bleu", "bourse", "branche", "brise", "broche", "campagne", "cause", "champ", "champion", "chevalier", "ciel", "clair", "clocher", "coffre", "colline", "commerce", "contrat", "crime", "exprimer", "falaise", "forêt", "four", "fuite", "gars", "glace", "griffe", "grotte", "herbe", "hiver", "insecte", "laine", "ligne", "lutte", "million", "mois", "montagne", "nature", "nuage", "océan", "oiseau", "panier", "parc", "pays", "paysage", "place", "plage", "plaque", "pluie", "plume", "poisson", "potager", "poule", "prairie", "proche", "procès", "queue", "racine", "rature", "regret", "rivière", "roche", "rocher", "récolte", "sable", "saison", "serpent", "société", "soleil", "soupçon", "temps", "tempête", "terre", "terreur", "tonnerre"],
    texte: "Je vais décrire la forêt derrière chez moi, c'est mon endroit préféré au monde. Il y a beaucoup d'arbres très grands et vieux, avec des branches pleines de feuilles vertes qui bougent avec le vent. Le ciel est bleu au-dessus et le soleil passe à travers les feuilles, ça fait de la lumière par terre. On entend les oiseaux qui chantent très fort et qui volent d'une branche à l'autre. Par terre, il y a de la mousse douce, de l'herbe et des petites fleurs jaunes et blanches. En automne, les feuilles tombent et deviennent rouges, oranges et jaunes, c'est très beau à voir. Il y a aussi un petit lac où nagent des poissons et des canards tranquilles. Parfois, on voit un écureuil qui court vite ou un lapin qui se cache dans les buissons. L'air sent bon la nature et la terre mouillée après la pluie. Quand il pleut, on entend la pluie tomber sur les feuilles. C'est calme, paisible et reposant. J'aime y aller pour me promener, respirer profondément et me reposer loin du bruit.",
    motsUtilises: ["automne", "bleu", "branche", "ciel", "forêt", "nature", "pluie", "soleil", "terre"],
    exercices: [
      { categorie: "Famille de mots", indice: "animalier", reponse: "animal" },
      { categorie: "Famille de mots", indice: "arboré", reponse: "arbre" },
      { categorie: "Famille de mots", indice: "montagneux", reponse: "montagne" },
      { categorie: "Famille de mots", indice: "sablonneux", reponse: "sable" },
      { categorie: "Famille de mots", indice: "pluvieux", reponse: "pluie" },
      { categorie: "Synonymes", indice: "rivage", reponse: "plage" },
      { categorie: "Synonymes", indice: "faune", reponse: "animal" },
      { categorie: "Synonymes", indice: "bois", reponse: "forêt" },
      { categorie: "Synonymes", indice: "cours d'eau", reponse: "rivière" },
      { categorie: "Synonymes", indice: "mont", reponse: "montagne" },
      { categorie: "Antonymes", indice: "ville", reponse: "campagne" },
      { categorie: "Antonymes", indice: "été", reponse: "hiver" },
      { categorie: "Antonymes", indice: "sommet", reponse: "vallée" },
      { categorie: "Antonymes", indice: "terre", reponse: "ciel" },
      { categorie: "Antonymes", indice: "mer", reponse: "terre" },
      { categorie: "Féminin", indice: "absent", reponse: "absente" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
      { categorie: "Féminin", indice: "acheteur", reponse: "acheteuse" },
    ]
  },
  {
    id: 6,
    titre: "6. La ville, les lieux et les transports",
    vocabulaire: ["acteur", "actrice", "agréable", "aimable", "amateur", "amatrice", "ambulance", "anneau", "apparence", "arrêt", "artisan", "artisane", "atelier", "attention", "auberge", "autobus", "bambou", "banlieue", "barque", "bonté", "bénéfice", "bûche", "caprice", "caravane", "carrière", "caserne", "centre", "cercle", "chaleur", "cheminée", "chimie", "cime", "cinéma", "cirque", "cloche", "drame", "ennemi", "ennemie", "foire", "folie", "fond", "foule", "fusil", "fusée", "gare", "gifle", "gorge", "grave", "groupe", "guerre", "gueule", "haie", "horaire", "humide", "hôtel", "invitée", "lance", "lieu", "menace", "milieu", "moine", "noirceur", "noter", "page", "passage", "patiente", "pierre", "piscine", "piste", "piège", "pont", "portrait", "portée", "poème", "prison", "prochain", "prochaine", "quai", "rapide", "rapport", "revanche", "rigueur", "rouge", "route", "rue", "région", "réussite", "silence", "sobre", "sport", "station", "séance", "sévérité", "terme", "tunnel", "vase", "victime", "village", "voile", "voilier"],
    texte: "Je vais décrire ma ville. J'habite dans un petit village pas très loin de la grande ville. Ce n'est pas très grand, mais on y trouve tout ce qu'il faut. Dans le centre, il y a une gare, une épicerie, une école, une bibliothèque et une piscine où on va l'été pour se baigner. Il y a beaucoup de rues avec des maisons de toutes les couleurs, avec des jardins devant. Le matin, il y a beaucoup de voitures et d'autobus qui passent dans les rues principales. Les gens vont au travail ou à l'école, ils marchent vite. Il y a aussi une grande place où les enfants jouent au ballon après les cours. Il y a un vieux pont en pierre qui traverse la petite rivière. Le soir, les lumières des maisons s'allument et c'est joli à regarder depuis la colline. J'aime le bruit de la foule au marché le samedi matin. J'aime aussi le silence du soir quand tout devient calme. C'est un endroit agréable où il fait bon vivre, entre la ville et la campagne. On s'y sent bien et en sécurité.",
    motsUtilises: ["agréable", "centre", "foule", "gare", "pierre", "piscine", "pont", "silence", "village", "épicerie"],
    exercices: [
      { categorie: "Famille de mots", indice: "villageois", reponse: "village" },
      { categorie: "Famille de mots", indice: "routier", reponse: "route" },
      { categorie: "Famille de mots", indice: "ferroviaire", reponse: "gare" },
      { categorie: "Famille de mots", indice: "stationnement", reponse: "station" },
      { categorie: "Famille de mots", indice: "central", reponse: "centre" },
      { categorie: "Synonymes", indice: "hameau", reponse: "village" },
      { categorie: "Synonymes", indice: "chemin", reponse: "route" },
      { categorie: "Synonymes", indice: "aérogare", reponse: "gare" },
      { categorie: "Synonymes", indice: "arrêt", reponse: "station" },
      { categorie: "Synonymes", indice: "milieu", reponse: "centre" },
      { categorie: "Antonymes", indice: "paix", reponse: "guerre" },
      { categorie: "Antonymes", indice: "bruit", reponse: "silence" },
      { categorie: "Antonymes", indice: "lent", reponse: "rapide" },
      { categorie: "Antonymes", indice: "ville", reponse: "village" },
      { categorie: "Antonymes", indice: "périphérie", reponse: "centre" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "ennemi", reponse: "ennemie" },
      { categorie: "Féminin", indice: "prochain", reponse: "prochaine" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
    ]
  },
  {
    id: 7,
    titre: "7. Le temps, les nombres et l'espace",
    vocabulaire: ["accueil", "agence", "ailleurs", "alcool", "amateur", "amatrice", "année", "après", "armée", "artisan", "artisane", "aucun", "aucune", "aurore", "aussi", "avenir", "baisse", "bande", "bord", "brûlure", "budget", "cacao", "centaine", "chêne", "destin", "devant", "distance", "domicile", "durée", "enfance", "extrait", "extrême", "facilité", "faible", "fauteuil", "fortune", "franchir", "futur", "genre", "geste", "génie", "général", "heure", "hockey", "hors", "instant", "jamais", "journal", "journée", "lien", "logement", "loi", "lâche", "légume", "maillot", "majesté", "majorité", "manche", "midi", "miette", "moitié", "moment", "mousse", "nom", "nombre", "nord", "nuit", "ombre", "palais", "passé", "pendre", "pente", "poubelle", "premier", "première", "presse", "prudence", "présence", "présent", "présente", "punition", "quantité", "rare", "rasoir", "reste", "retard", "régulier", "réunion", "sapin", "secret", "siège", "soudain", "sous", "supplice", "séjour", "sûreté", "tard", "verrou", "vitesse", "vitre"],
    texte: "Je vais décrire le temps qui passe. Le matin, l'aurore se lève doucement et le jour commence petit à petit. On regarde l'heure sur le réveil pour ne pas être en retard à l'école. On déjeune vite et on part en courant. La journée passe très vite entre les cours, les jeux à la récréation, les repas et les devoirs à la maison. Le soir, la nuit arrive, il fait noir et on voit les étoiles dans le ciel. On est fatigué et on va se coucher. Les saisons changent aussi pendant l'année, on le voit bien. L'année est divisée en douze mois et chaque mois a son moment spécial, comme Noël en décembre ou les vacances en été. Quand on est enfant, on trouve que le temps est très long avant les vacances. Quand on grandit, on trouve qu'il passe de plus en plus vite. Le passé est derrière nous, on ne peut plus y retourner. Le présent, c'est maintenant, ce qu'on vit. Et l'avenir est devant nous, on ne le connaît pas encore. Il faut profiter de chaque instant et de chaque jour qui passe.",
    motsUtilises: ["aussi", "devant", "instant", "journée", "moment", "nuit", "passé", "présent", "retard"],
    exercices: [
      { categorie: "Famille de mots", indice: "annuel", reponse: "année" },
      { categorie: "Famille de mots", indice: "horaire", reponse: "heure" },
      { categorie: "Famille de mots", indice: "momentané", reponse: "moment" },
      { categorie: "Famille de mots", indice: "durable", reponse: "durée" },
      { categorie: "Famille de mots", indice: "instantané", reponse: "instant" },
      { categorie: "Synonymes", indice: "an", reponse: "année" },
      { categorie: "Synonymes", indice: "seconde", reponse: "moment" },
      { categorie: "Synonymes", indice: "futur", reponse: "avenir" },
      { categorie: "Synonymes", indice: "maintenant", reponse: "présent" },
      { categorie: "Synonymes", indice: "époque", reponse: "année" },
      { categorie: "Antonymes", indice: "futur", reponse: "passé" },
      { categorie: "Antonymes", indice: "avant", reponse: "après" },
      { categorie: "Antonymes", indice: "tôt", reponse: "tard" },
      { categorie: "Antonymes", indice: "absent", reponse: "présent" },
      { categorie: "Antonymes", indice: "tout", reponse: "aucun" },
      { categorie: "Féminin", indice: "présent", reponse: "présente" },
      { categorie: "Féminin", indice: "aucun", reponse: "aucune" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "premier", reponse: "première" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
    ]
  },
  {
    id: 8,
    titre: "8. Les actions et les verbes du quotidien",
    vocabulaire: ["aboiement", "accepter", "accuser", "admettre", "admirer", "adresse", "affaire", "aide", "amateur", "amatrice", "amener", "ancre", "ancêtre", "angle", "annonce", "annoncer", "apprendre", "artisan", "artisane", "astre", "attaque", "attendre", "auditrice", "averse", "avertir", "aveugle", "baiser", "battre", "bien-être", "calcul", "caneton", "chercher", "choisir", "combat", "commencer", "conseil", "consigne", "création", "céder", "demande", "dessin", "dessiner", "dispute", "don", "enlever", "ennemi", "ennemie", "excuse", "fabriquer", "faire", "faveur", "façade", "flocon", "forme", "frisson", "fête", "gagner", "garantie", "goût", "grimace", "guérir", "habiller", "hasard", "inutile", "jugement", "klaxon", "luxe", "marche", "marée", "masse", "mesure", "mise", "modèle", "nage", "ordre", "ouvrir", "parfum", "pleur", "pouvoir", "poésie", "premier", "première", "rang", "refuge", "refus", "regard", "rentrée", "saleté", "sauvage", "savant", "siècle", "souci", "souffrir", "soupir", "sourire", "souvenir", "succès", "sérieuse", "sérieux", "tombe"],
    texte: "Hier, j'ai vécu une petite aventure qui m'a marqué. Vers quatre heures de l'après-midi, j'entendais un aboiement fort et triste derrière la maison, près du garage. J'ai décidé d'aller voir ce que c'était, même si j'avais un peu peur. C'était un petit chien brun, tout seul, qui était perdu. Il tremblait et il ne voulait pas bouger, il restait dans un coin. J'ai essayé de l'approcher doucement en lui parlant avec une voix calme. Je lui ai donné un peu d'eau fraîche et un petit biscuit que j'avais dans ma poche. Ensuite, j'ai cherché son propriétaire dans le quartier en marchant avec lui. J'ai demandé de l'aide à ma voisine qui m'a donné un bon conseil très utile. Elle m'a dit de mettre une annonce avec une photo sur le groupe du village sur internet. Une heure plus tard, une dame est arrivée en courant, essoufflée. C'était sa maîtresse. Elle était très contente et presque en larmes. Le chien a sauté de joie en la voyant. J'étais fier d'avoir pu aider. Le soir, j'ai raconté mon histoire à ma famille qui m'a félicité et serré dans ses bras.",
    motsUtilises: ["aboiement", "annonce", "conseil"],
    exercices: [
      { categorie: "Famille de mots", indice: "acceptation", reponse: "accepter" },
      { categorie: "Famille de mots", indice: "accusation", reponse: "accuser" },
      { categorie: "Famille de mots", indice: "dessinateur", reponse: "dessin" },
      { categorie: "Famille de mots", indice: "travailleur", reponse: "travail" },
      { categorie: "Famille de mots", indice: "créatif", reponse: "création" },
      { categorie: "Synonymes", indice: "débuter", reponse: "commencer" },
      { categorie: "Synonymes", indice: "fouiller", reponse: "chercher" },
      { categorie: "Synonymes", indice: "construire", reponse: "fabriquer" },
      { categorie: "Synonymes", indice: "remporter", reponse: "gagner" },
      { categorie: "Synonymes", indice: "mémoire", reponse: "souvenir" },
      { categorie: "Antonymes", indice: "refuser", reponse: "accepter" },
      { categorie: "Antonymes", indice: "finir", reponse: "commencer" },
      { categorie: "Antonymes", indice: "oublier", reponse: "souvenir" },
      { categorie: "Antonymes", indice: "fermer", reponse: "ouvrir" },
      { categorie: "Antonymes", indice: "perdre", reponse: "gagner" },
      { categorie: "Féminin", indice: "premier", reponse: "première" },
      { categorie: "Féminin", indice: "ennemi", reponse: "ennemie" },
      { categorie: "Féminin", indice: "sérieux", reponse: "sérieuse" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
    ]
  },
  {
    id: 9,
    titre: "9. La nourriture, les boissons et les objets du quotidien",
    vocabulaire: ["abondance", "acteur", "actrice", "aliment", "allumette", "amateur", "amatrice", "amusant", "antiquité", "appareil", "appel", "arachide", "artisan", "artisane", "assiette", "auditeur", "baignade", "banane", "bataille", "besoin", "beurre", "biscuit", "blague", "boisson", "bonbon", "bouquet", "bureau", "cadeau", "caresse", "cerise", "choc", "château", "clé", "concert", "corde", "coton", "crème", "demeurer", "dessert", "deviner", "douce", "doux", "décision", "déraison", "facture", "fardeau", "ficelle", "file", "flamme", "flûte", "frais", "fraîche", "fromage", "fruit", "fumée", "gant", "gâteau", "hache", "horizon", "huile", "idiot", "immobile", "jus", "justice", "lait", "lueur", "légende", "léger", "machine", "manoeuvre", "manteau", "miel", "morceau", "mélodie", "nappe", "niveau", "pain", "papier", "paquet", "pareil", "pelle", "pinceau", "plat", "plein", "poignée", "pomme", "pression", "recette", "remise", "repas", "ronce", "rythme", "régime", "réveil", "sein", "serrure", "simple", "sirène", "sucre", "timbre"],
    texte: "Ce week-end, j'ai cuisiné avec ma grand-mère dans sa petite cuisine. C'était la première fois que je faisais un gâteau tout seul avec elle. On a voulu faire un gâteau au chocolat, c'est mon préféré depuis toujours. On a pris du beurre, du sucre, du lait, des oeufs et de la farine que ma grand-mère avait achetés le matin. On a tout mélangé dans un grand bol jaune avec une cuillère en bois. Il fallait faire attention à suivre la recette mot pour mot pour ne pas se tromper. Ma grand-mère a allumé le four qui était déjà chaud. On a mis la pâte dans un moule rond et on l'a mis au four. Pendant que le gâteau cuisait, ça sentait très bon dans toute la maison, une odeur douce de chocolat. On a préparé aussi une boisson avec du jus de fruits frais et sucré. Quand le gâteau a été prêt, on l'a sorti et on l'a laissé refroidir sur la table près de la fenêtre. Ensuite, on l'a coupé en morceaux et on l'a mis sur une belle assiette blanche. On l'a mangé ensemble dans la cuisine en parlant. C'était doux, moelleux et délicieux. C'était un très bon moment de partage en famille que je n'oublierai pas.",
    motsUtilises: ["assiette", "beurre", "boisson", "douce", "doux", "frais", "gâteau", "jus", "lait", "recette", "sucre"],
    exercices: [
      { categorie: "Famille de mots", indice: "laitier", reponse: "lait" },
      { categorie: "Famille de mots", indice: "fruité", reponse: "fruit" },
      { categorie: "Famille de mots", indice: "sucré", reponse: "sucre" },
      { categorie: "Famille de mots", indice: "boulanger", reponse: "pain" },
      { categorie: "Famille de mots", indice: "fromager", reponse: "fromage" },
      { categorie: "Synonymes", indice: "friandise", reponse: "bonbon" },
      { categorie: "Synonymes", indice: "mets", reponse: "plat" },
      { categorie: "Synonymes", indice: "gourmandise", reponse: "dessert" },
      { categorie: "Synonymes", indice: "breuvage", reponse: "boisson" },
      { categorie: "Synonymes", indice: "nourriture", reponse: "aliment" },
      { categorie: "Antonymes", indice: "amer", reponse: "doux" },
      { categorie: "Antonymes", indice: "chaud", reponse: "frais" },
      { categorie: "Antonymes", indice: "vide", reponse: "plein" },
      { categorie: "Antonymes", indice: "compliqué", reponse: "simple" },
      { categorie: "Antonymes", indice: "dur", reponse: "douce" },
      { categorie: "Féminin", indice: "doux", reponse: "douce" },
      { categorie: "Féminin", indice: "frais", reponse: "fraîche" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
    ]
  },
  {
    id: 10,
    titre: "10. Les idées, les qualités, la société et le langage abstrait",
    vocabulaire: ["absence", "acheteur", "acheteuse", "acteur", "activité", "actrice", "addition", "amateur", "amatrice", "artisan", "artisane", "audace", "avantage", "barrière", "bruit", "chance", "chanson", "chiffre", "citoyen", "contenu", "contrôle", "crainte", "d'accord", "danger", "degré", "document", "doute", "douter", "effort", "exemple", "exploit", "face", "faute", "foin", "fonction", "force", "gloire", "grâce", "gêne", "habit", "habitude", "individu", "instinct", "intérêt", "largeur", "liberté", "limite", "liste", "longueur", "manque", "mariage", "matière", "mensonge", "message", "miracle", "misère", "mode", "mort", "moyen", "mérite", "méthode", "nouveau", "nouvelle", "objectif", "obstacle", "oeuvre", "opinion", "orgueil", "paix", "panique", "pauvreté", "perte", "pitié", "plafond", "point", "prix", "produit", "profit", "promesse", "raison", "religion", "remords", "respect", "richesse", "risque", "roman", "réaction", "service", "songe", "source", "surface", "sécurité", "série", "tact", "talent", "trahison", "trajet", "tâche", "valeur", "victoire"],
    texte: "L'an dernier, j'ai eu une expérience qui a changé ma vie et dont je me souviens encore. Depuis toujours, j'avais peur de parler devant les autres élèves de ma classe. À chaque fois que je devais parler en classe ou répondre à une question, j'avais le coeur qui battait très vite et les mains qui tremblaient un peu. Un jour, mon enseignant m'a donné un petit rôle dans une pièce de théâtre de l'école pour la fête de fin d'année. J'ai eu beaucoup de crainte au début et j'ai voulu dire non tout de suite. Mais mes parents m'ont encouragé à faire un effort et à essayer quand même. J'ai appris mon texte chaque soir dans ma chambre. Le jour du spectacle, la salle était pleine et j'ai vu mes parents dans la salle qui me souriaient et qui me faisaient un signe. J'ai respiré fort et j'ai commencé à parler doucement. Au début, ma voix tremblait un peu, mais ensuite j'ai pris confiance. À la fin, tout le monde a applaudi très fort. J'ai ressenti une grande joie et une grande fierté dans mon coeur. J'ai compris que le courage aide à grandir et à se dépasser.",
    motsUtilises: ["crainte", "effort"],
    exercices: [
      { categorie: "Famille de mots", indice: "craintif", reponse: "crainte" },
      { categorie: "Famille de mots", indice: "dangereux", reponse: "danger" },
      { categorie: "Famille de mots", indice: "libre", reponse: "liberté" },
      { categorie: "Famille de mots", indice: "pauvre", reponse: "pauvreté" },
      { categorie: "Famille de mots", indice: "riche", reponse: "richesse" },
      { categorie: "Synonymes", indice: "peur", reponse: "crainte" },
      { categorie: "Synonymes", indice: "risque", reponse: "danger" },
      { categorie: "Synonymes", indice: "fortune", reponse: "richesse" },
      { categorie: "Synonymes", indice: "opportunité", reponse: "chance" },
      { categorie: "Synonymes", indice: "modèle", reponse: "exemple" },
      { categorie: "Antonymes", indice: "vérité", reponse: "mensonge" },
      { categorie: "Antonymes", indice: "richesse", reponse: "pauvreté" },
      { categorie: "Antonymes", indice: "guerre", reponse: "paix" },
      { categorie: "Antonymes", indice: "faiblesse", reponse: "force" },
      { categorie: "Antonymes", indice: "danger", reponse: "sécurité" },
      { categorie: "Féminin", indice: "nouveau", reponse: "nouvelle" },
      { categorie: "Féminin", indice: "artisan", reponse: "artisane" },
      { categorie: "Féminin", indice: "amateur", reponse: "amatrice" },
      { categorie: "Féminin", indice: "acteur", reponse: "actrice" },
      { categorie: "Féminin", indice: "acheteur", reponse: "acheteuse" },
    ]
  },
];